name: Change log check
on:
  pull_request:
    types: [assigned, opened, synchronize, reopened, labeled, unlabeled]
    branches:
      - main

env:
  python-version: 3.12

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # Fetch all history
          fetch-depth: '0'

      - name: Setup uv
        uses: plone/meta/.github/actions/setup_uv@2.x
        with:
          python-version: ${{ env.python-version }}
      - name: Check for presence of a Change Log fragment (only pull requests)
        if: github.event_name == 'pull_request'
        run: |
          git fetch --no-tags origin ${{ github.base_ref }}
          uvx towncrier check  --compare-with origin/${{ github.base_ref }} --config pyproject.toml --dir .
